config/routes.rb
Rails.application.routes.draw do
  resources :universities do
    scope module: 'universities' do
    	resources :courses
      resources :alimentations
      resources :student_entities
      resources :teachers
      resources :campus
    end
  end
end

app/models/alimentation.rb
class Alimentation < ApplicationRecord
  belongs_to :university
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campus.rb
class Campus < ApplicationRecord
  self.table_name = 'campus'

  belongs_to :university
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :university
end

app/models/student_entity.rb
class StudentEntity < ApplicationRecord
  belongs_to :university
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :university
end

app/models/university.rb
class University < ApplicationRecord
  has_many :courses, dependent: :destroy
  has_many :alimentations, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :teachers, dependent: :destroy
  has_many :student_entities, dependent: :destroy
  has_many :campus, dependent: :destroy, class_name: 'Campus'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :university
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/universities/alimentations_controller.rb
class Universities::AlimentationsController < Universities::BaseController
  before_action :set_current_university

  def index
    @alimentations = @current_university.alimentations
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def course_params
    params.require(:alimentations).permit(:name, :description, :condition, :dependency_name, :uf, :creation_date)
  end
end

app/controllers/universities/base_controller.rb
class Universities::BaseController < ApplicationController
  def set_current_university
    @current_university ||= University.find(params[:university_id] || params[:id])
  end
end

app/controllers/universities/campus_controller.rb
class Universities::CampusController < Universities::BaseController
  before_action :set_current_university

  def index
    @campus = @current_university.campus
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def campus_params
    params.require(:campus).permit(:name, :description, :condition, :dependency_name, :uf, :creation_date)
  end
end

app/controllers/universities/courses_controller.rb
class Universities::CoursesController < Universities::BaseController
  before_action :set_current_university

  def index
    @courses = @current_university.courses
  end

  def show
  end

  def new
    @course = Course.new(university: @current_university)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to university_courses_path(@current_university), notice: "Curso criado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
  end

  def destroy
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :difficulty).merge(university: @current_university)
  end
end

app/controllers/universities/student_entities_controller.rb
class Universities::StudentEntitiesController < Universities::BaseController
  before_action :set_current_university

  def index
    @student_entities = @current_university.student_entities
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def teacher_params
    params.require(:student_entity).permit(:name, :description, :condition, :dependency_name, :uf, :creation_date)
  end
end

app/controllers/universities/teachers_controller.rb
class Universities::TeachersController < Universities::BaseController
  before_action :set_current_university

  def index
    @teachers = @current_university.teachers
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name, :description, :condition, :dependency_name, :uf, :creation_date)
  end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: %i[ show edit update destroy ]

  def index
    @universities = University.all
  end

  def show
  end

  def new
    @university = University.new
  end

  def edit
  end

  def create
    @university = University.new(university_params)

    if @university.save
      redirect_to @university, notice: "University was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @university.update(university_params)
      redirect_to @university, notice: "University was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @university.destroy

    redirect_to universities_url, notice: "University was successfully destroyed."
  end

  private
    def set_university
      @university = University.find(params[:id])
    end

    def university_params
      params.require(:university).permit(:name, :acronyn, :description, :condition, :dependency_name, :uf, :creation_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityCentral</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/universities/main.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"
    link rel="icon" href="/favicon.ico" type="image/x-icon"
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"

  body
    #wrapper
      = render 'layouts/universities/sidebar'
      .gray-bg#page-wrapper
        = render 'layouts/universities/topbar'
        = yield

app/views/universities/_form.slim
= simple_form_for(university, html: { class: 'form-inline' })  do |f|
  - if university.errors.any?
    #error_explanation
      h2
        = pluralize(university.errors.count, "error")
        | prohibited this university from being saved:
      ul
        - university.errors.full_messages.each do |message|
          li= message
  = f.input :name, label: 'Nome'
  = f.input :acronyn
  = f.input :description
  = f.input :condition
  = f.input :dependency_name
  = f.input :uf
  = f.input :creation_date

  br
  = f.button :submit, "Salvar", class: "btn btn-primary btn-lg float-right"

app/views/universities/alimentations/index.slim
.container
  .jumbotron
    h1.text-center Central de Universidades


  h2 Lista de ambientes de alimentação da #{@current_university.name}
  table.table
    thead.thead-ligh
      tr
        th Nome
        th Descrição
        th colspan="3"
    tbody
      - @alimentations.each do |alimentation|
        tr
          td= alimentation.name
          td= alimentation.description
          td= link_to 'Show', alimentation
          td= link_to 'Edit', edit_alimentation_path(alimentation)
          td= link_to 'Destroy', alimentation, method: :delete, data: { confirm: 'Are you sure?'}
  br/
  = link_to 'Cadastrar novo ambiente de alimentação', new_university_alimentation_path(@current_university)
  br
  = link_to 'Voltar', university_path(@current_university), class: "btn btn-primary btn-lg"

app/views/universities/campus/index.slim
.container
  .jumbotron
    h1.text-center Central de Universidades


  h2 Lista de campus da #{@current_university.name}
  table.table
    thead.thead-ligh
      tr
        th Nome
        th Descrição
        th Endereço
        th Cidade
        th Estado
        th CEP
        th colspan="3"
    tbody
      - @campus.each do |campu|
        tr
          td= campu.name
          td= campu.description
          td= campu.address
          td= campu.city
          td= campu.state
          td= campu.postal_code
          td= link_to 'Show', campu
          td= link_to 'Edit', edit_campu_path(campu)
          td= link_to 'Destroy', alimentation, method: :delete, data: { confirm: 'Are you sure?'}
  br/
  = link_to 'Cadastrar novo campus para ' + @current_university.name, new_university_campu_path(@current_university)
  br
  = link_to 'Voltar', university_path(@current_university), class: "btn btn-primary btn-lg"

app/views/universities/courses/_form.slim
= simple_form_for(course, url: url, method: method, html: { class: 'form-inline' })  do |f|
  - if course.errors.any?
    #error_explanation
      h2
        = pluralize(course.errors.count, "error")
        | prohibited this course from being saved:
      ul
        - course.errors.full_messages.each do |message|
          li= message
  = f.input :name, label: 'Nome'
  = f.input :description, label: 'Descrição'
  = f.input :difficulty, label: 'Dificuldade'

  br
  = f.button :submit, "Salvar", class: "btn btn-primary btn-lg float-right"

app/views/universities/courses/index.slim
.container
  .jumbotron
    h1.text-center Central de Universidades


  h2 Lista de Cursos da #{@current_university.name}
  table.table
    thead.thead-ligh
      tr
        th Nome
        th Descrição
        th Dificuldade
        th colspan="3"
    tbody
      - @courses.each do |course|
        tr
          td= course.name
          td= course.description
          td= course.difficulty
          td= link_to 'Show', university_course_path(@current_university, course)
          td= link_to 'Edit', edit_university_course_path(@current_university, course)
  br/
  = link_to 'Cadastrar novo curso', new_university_course_path(@current_university)
  br
  = link_to 'Voltar', university_path(@current_university), class: "btn btn-primary btn-lg"

app/views/universities/courses/new.slim
.container
  .jumbotron
    h1.text-center Central de Universidades

  h1 Cadastrar Curso da #{@current_university.name}
  = render partial: 'form', locals: { course: @course, url: university_courses_path, method: :post }
  br
  = link_to 'Back', university_courses_path(@current_university), class: "btn btn-primary btn-lg float-right"

app/views/universities/edit.slim
.container
  .jumbotron
    h1.text-center Central de Universidades

	h1 Editando #{@university.name}
  = render 'form', university: @university

  br
    = link_to 'Mostrar', @university, class: "btn btn-primary btn-lg"
  br
    = link_to 'Voltar', universities_path, class: "btn btn-primary btn-lg"

app/views/universities/index.slim
.container
  .jumbotron
    h1.text-center Central de Universidades


  h1 Lista de Universidades
  table.table
    thead.thead-ligh
      tr
        th Name
        th Acronyn
        th Description
        th Condition
        th Dependency name
        th Uf
        th Creation date
        th colspan="3"
    tbody
      - @universities.each do |university|
        tr
          td= university.name
          td= university.acronyn
          td= university.description
          td= university.condition
          td= university.dependency_name
          td= university.uf
          td= university.creation_date
          td= link_to 'Show', university
          td= link_to 'Edit', edit_university_path(university)
          td= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?'}
  br/
  = link_to 'New University', new_university_path

app/views/universities/new.slim
.container
  .jumbotron
    h1.text-center Central de Universidades

  h1 Cadastrar Universidade
  = render 'form', university: @university
  br
  = link_to 'Back', universities_path, class: "btn btn-primary btn-lg float-right"

app/views/universities/show.slim
.container
  .jumbotron
    h1.text-center Central de Universidades
  br

  p#notice= notice
  p
    strong Nome:
    = @university.name
  p
    strong Sigla:
    = @university.acronyn
  p
    strong Descrição:
    = @university.description
  p
    strong Condição:
    = @university.condition
  p
    strong Estado:
    = @university.uf
  p
    strong Data de Criação:
    = @university.creation_date

  = link_to 'Editar', edit_university_path(@university), class: "btn btn-primary btn-lg"
  |   
  = link_to 'Voltar', universities_path, class: "btn btn-primary btn-lg"

  br
  br

  = link_to university_courses_path(@university)
    .btn.btn-primary.btn-lg.ml-2 Cursos

  = link_to university_teachers_path(@university)
    .btn.btn-primary.btn-lg.pl-6 Professores

  = link_to university_campus_path(@university)
    .btn.btn-primary.btn-lg.pl-6 Campus

  = link_to university_student_entities_path(@university)
    .btn.btn-primary.btn-lg.pl-6 Entidades

  = link_to university_alimentations_path(@university)
    .btn.btn-primary.btn-lg.pl-6 Alimentação

app/views/universities/student_entities/index.slim
.container
  .jumbotron
    h1.text-center Central de Universidades


  h2 Lista de ambientes de entidades da #{@current_university.name}
  table.table
    thead.thead-ligh
      tr
        th Nome
        th Descrição
        th colspan="3"
    tbody
      - @student_entities.each do |student_entity|
        tr
          td= student_entity.name
          td= student_entity.description
          td= link_to 'Show', student_entity
          td= link_to 'Edit', edit_student_entity_path(student_entity)
          td= link_to 'Destroy', student_entity, method: :delete, data: { confirm: 'Are you sure?'}
  br/
  = link_to 'Cadastrar nova entidade para ' + @current_university.name, new_university_student_entity_path(@current_university)
  br
  = link_to 'Voltar', university_path(@current_university), class: "btn btn-primary btn-lg"

app/views/universities/teachers/index.slim
.container
  .jumbotron
    h1.text-center Central de Universidades


  h2 Lista de professores #{@current_university.name}
  table.table
    thead.thead-ligh
      tr
        th Nome
        th Descrição
        th colspan="3"
    tbody
      - @teachers.each do |teacher|
        tr
          td= teacher.name
          td= teacher.description
          td= link_to 'Show', teacher
          td= link_to 'Edit', edit_teacher_path(teacher)
          td= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?'}
  br/
  = link_to 'Cadastrar nova entidade para ' + @current_university.name, new_university_teacher_path(@current_university)
  br
  = link_to 'Voltar', university_path(@current_university), class: "btn btn-primary btn-lg"